data:
  dataset: cifar10
  batch_size: 64
  crop_scale: [1.0, 1.0]  # no cropping for tiny images
  crop_size: 32
  color_jitter_strength: 0.0
  image_folder: cifar10  # or wherever your CIFAR is stored
  num_workers: 4
  pin_mem: true
  root_path: ./data
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: true

logging:
  folder: ./output/cifar10_uncertainty
  write_tag: jepa_uncertainty

mask:
  mask_type: uncertainty_guided  # this is the key!
  n_contexts: 2
  n_targets: 4                   # fewer blocks = safer
  context_mask_scale: [0.1, 0.2]  # tiny blocks
  enc_mask_scale: [0.1, 0.2] 
  pred_mask_scale: [0.1, 0.2]
  target_mask_scale: [0.1, 0.2]
  aspect_ratio: [0.9, 1.1]       # close to square
  allow_overlap: False
  patch_size: 4
  min_keep: 1
  num_enc_masks: 1
  num_pred_masks: 1

meta:
  model_name: vit_small
  pred_depth: 4
  pred_emb_dim: 192
  use_bfloat16: false
  load_checkpoint: false
  read_checkpoint: null
  copy_data: false

optimization:
  epochs: 10
  lr: 0.0005
  start_lr: 0.0002
  final_lr: 1.0e-5
  warmup: 2
  weight_decay: 0.05
  final_weight_decay: 0.05
  ema: [0.996, 1.0]
  ipe_scale: 1.0
